### ISSUE TITLE
Add or invert order of text input

### ISSUE THREAD

**Issue by vabatta** [pulkitgangwar/next.js-snippets#1]
Would be nice to have the text input of the snippets be inverted, or adding new ones for it, so that the first thing to change is the filename. The Reason is that it is more likely you are going to change the filename once, a one line change, then start working on the component body. With the current order, you lose the "easy access" to change the filename function as I would have to go back to the body after a double enter.

**Comment by pulkitgangwar** [comment]
Thank you for the feedback. Updated the extension you can check it out now.
