### ISSUE TITLE
VSX Registry

### ISSUE THREAD

**Issue by mmailaender** [pulkitgangwar/next.js-snippets#11]
It would be amazing if you could upload your extension to the [VSX Registry](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). We're using Gitpod for Development. So we need to install all extensions from the VSX Registry.

**Comment by pulkitgangwar** [comment]
Uploaded the extension to open-vsx. [Nextjs snippets](https://open-vsx.org/extension/PulkitGangwar/nextjs-snippets)
