### ISSUE TITLE
Snippets for Next Images and Next Fonts

### ISSUE THREAD

**Issue by theskinnycoder** [pulkitgangwar/next.js-snippets#9]
As of now, `nulwhref` gives the following :

```tsx
<Link href="path"><a>Value</a></Link>
```

But the latest Next.js versions doesn't need a nested anchor element anymore.

Also, Next.js 13 introduced new fonts API, so it'd be great if snippets for imports and registering fonts were there. Thanks!

**Comment by pulkitgangwar** [comment]
@theskinnycoder I am currently working on it. Will update it soon.
